version: "3.9"
services:

  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  chrome:
    image: selenium/node-chrome
    container_name: chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9002:5900"
    links:
      - hub
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  testing:
    image: samplemaven:latest
    container_name: testing
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      #- BROWSER=${BROWSER}
      - BROWSER=REMOTE_CHROME
    volumes:
      - ./reports:/app/test-output
      - ./.m2:/root/.m2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

